SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [Followup](
	[FollowupId] [int] IDENTITY(1,1) NOT NULL,
	[UserId] [int] NOT NULL,
	[ActivityDate] [datetime] NOT NULL,
	[JobApplicationId] [int] NOT NULL,
	[FollowupDescription] [varchar](MAX) NOT NULL
 CONSTRAINT [PK_Followup] PRIMARY KEY CLUSTERED 
(
	[FollowupId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

ALTER TABLE [Followup]  WITH CHECK ADD  CONSTRAINT [FK_Followup_IdentityUser] FOREIGN KEY([UserId])
REFERENCES [IdentityUser] ([Id])
GO

ALTER TABLE [Followup]  WITH CHECK ADD  CONSTRAINT [FK_Followup_JobApplication] FOREIGN KEY([JobApplicationId])
REFERENCES [JobApplication] ([JobApplicationId])
GO

SET ANSI_PADDING OFF
GO
